### ISSUE TITLE
Add a Button to the Front end with name "Create".

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Celebal-Internship#1]
Simply, just add a button to the front end using the index.html file and style the button if possible.

![Capture](https://user-images.githubusercontent.com/56088741/84570519-aa83d200-adab-11ea-95c8-6b05a01a91ec.PNG)

**Comment by rwt-akshat** [comment]
hello sameer,
I am ready to add the button part as i have worked using HTML, CSS and java Script.
Please assign this issue to me.
thanks

**Comment by sameersrivastava13** [comment]
That sounds great akshat.
Please go ahead.
i am assigning you the issue.
